language: node_js
node_js:
  - "12"
dist: angular-tour-of-heroes
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  #- ng build --prod --base-href https://jose55mase.github.io/sonarqube_and_travis/

deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  #github_token: $GITHUB_TOKEN
  #local_dir: dist/angular-tour-of-heroes
  on:
    branch: master


